name: PR CHECK

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build
        run: echo "Running build"

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v4
      - name: Run lint
        run: npm install && npm run lint
